/**
 * Generates src/generated/mathlive-bundled.css from the installed MathLive
 * package: the stock mathlive-static.css with every `url(fonts/X.woff2)`
 * rewritten to a base64 `data:` URI.
 *
 * Obsidian installs only main.js / manifest.json / styles.css, so font files
 * cannot ship alongside the plugin. Inlining them keeps the plugin a single
 * self-contained bundle and means MathLive never issues a network request.
 */
import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { dirname, join, resolve } from "path";
import { fileURLToPath } from "url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const mathlive = join(root, "node_modules", "mathlive");
const outFile = join(root, "src", "generated", "mathlive-bundled.css");

const css = readFileSync(join(mathlive, "mathlive-static.css"), "utf8");

let inlined = 0;
const withFonts = css.replace(/url\(fonts\/([A-Za-z0-9_-]+\.woff2)\)/g, (_m, file) => {
	const bytes = readFileSync(join(mathlive, "fonts", file));
	inlined += 1;
	return `url(data:font/woff2;base64,${bytes.toString("base64")})`;
});

const remaining = withFonts.match(/url\((?!data:)/g);
if (remaining) {
	throw new Error(`build-styles: ${remaining.length} non-inlined url() reference(s) remain`);
}

const banner =
	"/* GENERATED by scripts/build-styles.mjs - do not edit.\n" +
	"   Source: mathlive/mathlive-static.css with KaTeX fonts inlined as data URIs. */\n";

mkdirSync(dirname(outFile), { recursive: true });
writeFileSync(outFile, banner + withFonts, "utf8");

const kb = (Buffer.byteLength(banner + withFonts) / 1024).toFixed(0);
process.stdout.write(`build-styles: ${inlined} fonts inlined, ${kb} KB written to src/generated/mathlive-bundled.css\n`);
